# golangci-lint configuration for solver-lnk
# Run with: golangci-lint run

linters:
  enable:
    # Bug prevention
    - staticcheck     # Advanced static analysis
    - gosec           # Security issues
    - errcheck        # Unchecked errors
    - ineffassign     # Detects useless assignments
    - unused          # Unused code
    - nilerr          # Finds returning nil with non-nil error
    
    # Code quality
    - gocyclo         # Cyclomatic complexity
    - gocognit        # Cognitive complexity
    - dupl            # Code duplication
    - goconst         # Repeated strings that could be constants
    - misspell        # Spelling mistakes
    
    # Style
    - gofmt           # Formatting
    - goimports       # Import organization
    - revive          # Replacement for golint

linters-settings:
  gocyclo:
    min-complexity: 25
  gocognit:
    min-complexity: 50
  goconst:
    min-len: 3
    min-occurrences: 3
  dupl:
    threshold: 150
  revive:
    rules:
      - name: exported
        disabled: true  # Don't require comments on exported functions

issues:
  # Don't limit issues per linter
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    # Exclude test files from some linters
    - path: _test\.go
      linters:
        - dupl
        - gocyclo
        - gocognit
        - gosec
    # Exclude fuzz tests from complexity checks
    - path: fuzz_test\.go
      linters:
        - unparam
    # Exclude G115 (integer overflow) - these are safe conversions within expected ranges
    - linters:
        - gosec
      text: "G115:"

run:
  timeout: 5m
  tests: true
