// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/config.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CastleConfig represents input configuration for castle solver
type CastleConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current building levels (ALL buildings must be specified)
	BuildingLevels map[string]int32 `protobuf:"bytes,1,rep,name=building_levels,json=buildingLevels,proto3" json:"building_levels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Current resources
	Resources map[string]float64 `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	// Already researched technologies
	ResearchedTechnologies []string `protobuf:"bytes,3,rep,name=researched_technologies,json=researchedTechnologies,proto3" json:"researched_technologies,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CastleConfig) Reset() {
	*x = CastleConfig{}
	mi := &file_proto_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CastleConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastleConfig) ProtoMessage() {}

func (x *CastleConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastleConfig.ProtoReflect.Descriptor instead.
func (*CastleConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{0}
}

func (x *CastleConfig) GetBuildingLevels() map[string]int32 {
	if x != nil {
		return x.BuildingLevels
	}
	return nil
}

func (x *CastleConfig) GetResources() map[string]float64 {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *CastleConfig) GetResearchedTechnologies() []string {
	if x != nil {
		return x.ResearchedTechnologies
	}
	return nil
}

// UnitsConfig represents input configuration for units solver
type UnitsConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Available food for units (default: 4265)
	FoodAvailable int32 `protobuf:"varint,1,opt,name=food_available,json=foodAvailable,proto3" json:"food_available,omitempty"`
	// Resource production per hour (default: 1161)
	ResourceProductionPerHour int32 `protobuf:"varint,2,opt,name=resource_production_per_hour,json=resourceProductionPerHour,proto3" json:"resource_production_per_hour,omitempty"`
	// Market distance in fields (default: 25)
	MarketDistanceFields int32 `protobuf:"varint,3,opt,name=market_distance_fields,json=marketDistanceFields,proto3" json:"market_distance_fields,omitempty"`
	// Existing units (optional)
	ExistingUnits map[string]int32 `protobuf:"bytes,4,rep,name=existing_units,json=existingUnits,proto3" json:"existing_units,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnitsConfig) Reset() {
	*x = UnitsConfig{}
	mi := &file_proto_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitsConfig) ProtoMessage() {}

func (x *UnitsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitsConfig.ProtoReflect.Descriptor instead.
func (*UnitsConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{1}
}

func (x *UnitsConfig) GetFoodAvailable() int32 {
	if x != nil {
		return x.FoodAvailable
	}
	return 0
}

func (x *UnitsConfig) GetResourceProductionPerHour() int32 {
	if x != nil {
		return x.ResourceProductionPerHour
	}
	return 0
}

func (x *UnitsConfig) GetMarketDistanceFields() int32 {
	if x != nil {
		return x.MarketDistanceFields
	}
	return 0
}

func (x *UnitsConfig) GetExistingUnits() map[string]int32 {
	if x != nil {
		return x.ExistingUnits
	}
	return nil
}

var File_proto_config_proto protoreflect.FileDescriptor

const file_proto_config_proto_rawDesc = "" +
	"\n" +
	"\x12proto/config.proto\x12\x06config\"\xde\x02\n" +
	"\fCastleConfig\x12Q\n" +
	"\x0fbuilding_levels\x18\x01 \x03(\v2(.config.CastleConfig.BuildingLevelsEntryR\x0ebuildingLevels\x12A\n" +
	"\tresources\x18\x02 \x03(\v2#.config.CastleConfig.ResourcesEntryR\tresources\x127\n" +
	"\x17researched_technologies\x18\x03 \x03(\tR\x16researchedTechnologies\x1aA\n" +
	"\x13BuildingLevelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a<\n" +
	"\x0eResourcesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xbc\x02\n" +
	"\vUnitsConfig\x12%\n" +
	"\x0efood_available\x18\x01 \x01(\x05R\rfoodAvailable\x12?\n" +
	"\x1cresource_production_per_hour\x18\x02 \x01(\x05R\x19resourceProductionPerHour\x124\n" +
	"\x16market_distance_fields\x18\x03 \x01(\x05R\x14marketDistanceFields\x12M\n" +
	"\x0eexisting_units\x18\x04 \x03(\v2&.config.UnitsConfig.ExistingUnitsEntryR\rexistingUnits\x1a@\n" +
	"\x12ExistingUnitsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01B(Z&github.com/napolitain/solver-lnk/protob\x06proto3"

var (
	file_proto_config_proto_rawDescOnce sync.Once
	file_proto_config_proto_rawDescData []byte
)

func file_proto_config_proto_rawDescGZIP() []byte {
	file_proto_config_proto_rawDescOnce.Do(func() {
		file_proto_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_config_proto_rawDesc), len(file_proto_config_proto_rawDesc)))
	})
	return file_proto_config_proto_rawDescData
}

var file_proto_config_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_config_proto_goTypes = []any{
	(*CastleConfig)(nil), // 0: config.CastleConfig
	(*UnitsConfig)(nil),  // 1: config.UnitsConfig
	nil,                  // 2: config.CastleConfig.BuildingLevelsEntry
	nil,                  // 3: config.CastleConfig.ResourcesEntry
	nil,                  // 4: config.UnitsConfig.ExistingUnitsEntry
}
var file_proto_config_proto_depIdxs = []int32{
	2, // 0: config.CastleConfig.building_levels:type_name -> config.CastleConfig.BuildingLevelsEntry
	3, // 1: config.CastleConfig.resources:type_name -> config.CastleConfig.ResourcesEntry
	4, // 2: config.UnitsConfig.existing_units:type_name -> config.UnitsConfig.ExistingUnitsEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_config_proto_init() }
func file_proto_config_proto_init() {
	if File_proto_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_config_proto_rawDesc), len(file_proto_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_config_proto_goTypes,
		DependencyIndexes: file_proto_config_proto_depIdxs,
		MessageInfos:      file_proto_config_proto_msgTypes,
	}.Build()
	File_proto_config_proto = out.File
	file_proto_config_proto_goTypes = nil
	file_proto_config_proto_depIdxs = nil
}
