// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.1
// source: proto/config.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CastleSolverService_Solve_FullMethodName         = "/config.CastleSolverService/Solve"
	CastleSolverService_GetNextAction_FullMethodName = "/config.CastleSolverService/GetNextAction"
)

// CastleSolverServiceClient is the client API for CastleSolverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Castle Solver Service
type CastleSolverServiceClient interface {
	// Solve returns the optimal build order for a castle
	Solve(ctx context.Context, in *SolveRequest, opts ...grpc.CallOption) (*SolveResponse, error)
	// GetNextAction returns only the next immediate action (lightweight)
	GetNextAction(ctx context.Context, in *SolveRequest, opts ...grpc.CallOption) (*BuildingAction, error)
}

type castleSolverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCastleSolverServiceClient(cc grpc.ClientConnInterface) CastleSolverServiceClient {
	return &castleSolverServiceClient{cc}
}

func (c *castleSolverServiceClient) Solve(ctx context.Context, in *SolveRequest, opts ...grpc.CallOption) (*SolveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SolveResponse)
	err := c.cc.Invoke(ctx, CastleSolverService_Solve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *castleSolverServiceClient) GetNextAction(ctx context.Context, in *SolveRequest, opts ...grpc.CallOption) (*BuildingAction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildingAction)
	err := c.cc.Invoke(ctx, CastleSolverService_GetNextAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CastleSolverServiceServer is the server API for CastleSolverService service.
// All implementations must embed UnimplementedCastleSolverServiceServer
// for forward compatibility.
//
// Castle Solver Service
type CastleSolverServiceServer interface {
	// Solve returns the optimal build order for a castle
	Solve(context.Context, *SolveRequest) (*SolveResponse, error)
	// GetNextAction returns only the next immediate action (lightweight)
	GetNextAction(context.Context, *SolveRequest) (*BuildingAction, error)
	mustEmbedUnimplementedCastleSolverServiceServer()
}

// UnimplementedCastleSolverServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCastleSolverServiceServer struct{}

func (UnimplementedCastleSolverServiceServer) Solve(context.Context, *SolveRequest) (*SolveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Solve not implemented")
}
func (UnimplementedCastleSolverServiceServer) GetNextAction(context.Context, *SolveRequest) (*BuildingAction, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNextAction not implemented")
}
func (UnimplementedCastleSolverServiceServer) mustEmbedUnimplementedCastleSolverServiceServer() {}
func (UnimplementedCastleSolverServiceServer) testEmbeddedByValue()                             {}

// UnsafeCastleSolverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CastleSolverServiceServer will
// result in compilation errors.
type UnsafeCastleSolverServiceServer interface {
	mustEmbedUnimplementedCastleSolverServiceServer()
}

func RegisterCastleSolverServiceServer(s grpc.ServiceRegistrar, srv CastleSolverServiceServer) {
	// If the following call panics, it indicates UnimplementedCastleSolverServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CastleSolverService_ServiceDesc, srv)
}

func _CastleSolverService_Solve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CastleSolverServiceServer).Solve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CastleSolverService_Solve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CastleSolverServiceServer).Solve(ctx, req.(*SolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CastleSolverService_GetNextAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CastleSolverServiceServer).GetNextAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CastleSolverService_GetNextAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CastleSolverServiceServer).GetNextAction(ctx, req.(*SolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CastleSolverService_ServiceDesc is the grpc.ServiceDesc for CastleSolverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CastleSolverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "config.CastleSolverService",
	HandlerType: (*CastleSolverServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Solve",
			Handler:    _CastleSolverService_Solve_Handler,
		},
		{
			MethodName: "GetNextAction",
			Handler:    _CastleSolverService_GetNextAction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/config.proto",
}
